FROM python:3.11

WORKDIR /code

# Спочатку копіюємо requirements для кешування
COPY app/requirements.txt ./app/requirements.txt

# Встановлюємо залежності
RUN pip install --no-cache-dir -r app/requirements.txt

# Копіюємо весь інший код
COPY . .

# Запускаємо сервер
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]